name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Rust + wasm32
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal

      # Node (React)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: wasm-pack build wasm --target web --out-dir public/wasm
      - run: npm run build

      # gh-pages ブランチへ公開
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
