name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal

      # wasm-pack を取得
      - uses: taiki-e/install-action@v2   # ←★ここを追加
        with:
          tool: wasm-pack@0.12.1          # バージョン固定推奨

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: wasm-pack build wasm --target web --out-dir public/wasm
      - run: yarn build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build